name: PixelWorldProV2
main: "com.mcyzj.pixelworldpro.v2.core.Main"
version: '${version}'
author: dong&mcyzj
softdepend: [ Vault, PlaceholderAPI, PlayerPoints, PixelPlayerWorld, ShadowLevels, RealisticSeasons, WorldGuard, WorldEdit, ProtocolLib]
api-version: 1.13
folia-supported: true

runtime-libraries:
  libraries-folder: '@Server:libraries'  # 存放依赖的位置
  libraries:
    kotlin:
      groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib
      version: "1.9.20"
      repository: "https://maven.mcyzj.cn:445/repository/maven-public/"
    JiangLib_Bukkit:
      groupId: com.mcyzj.lib
      artifactId: jianglib-bukkit
      version: "1.0.0"
      repository: "https://maven.mcyzj.cn:445/repository/maven-public/"
    ProtocolLib:
      groupId: com.comphenix.protocol
      artifactId: ProtocolLib
      version: "4.8.0"
      repository: "https://repo.dmulloy2.net/repository/public/"
    gson:
      groupId: com.google.code.gson
      artifactId: gson
      version: "2.10"
    slf4j-api:
      groupId: org.slf4j
      artifactId: slf4j-api
      version: "1.7.22"
    slf4j-simple:
      groupId: org.slf4j
      artifactId: slf4j-simple
      version: "1.7.22"
    jedis:
      groupId: redis.clients
      artifactId: jedis
      version: "3.7.0"
    bcprov-lts8on:
      groupId: org.bouncycastle
      artifactId: bcprov-lts8on
      version: "2.73.3"
    pool2:
      groupId: org.apache.commons
      artifactId: commons-pool2
      version: "2.8.0"
    HikariCP:
      groupId: com.zaxxer
      artifactId: HikariCP
      version: "4.0.3"
    ormlite-core:
      groupId: com.j256.ormlite
      artifactId: ormlite-core
      version: "6.1"
    ormlite-jdbc:
      groupId: com.j256.ormlite
      artifactId: ormlite-jdbc
      version: "6.1"
    json:
      groupId: com.googlecode.json-simple
      artifactId: json-simple
      version: "1.1"